### ISSUE TITLE
mp3cast~ freeze Pd

### ISSUE THREAD

**Issue by Jackovic** [pd-externals/mp3cast#1]
To reproduce the freeze :
- start a stream to icecast2 server
- cut your network connection
=> Pd freeze

If the connection is restored, Pd is restored too.

**Comment by reduzent** [comment]
It didn't freeze immediately, but it waited quite long until it gave up. On my computer, I measured 2 minutes. 

I added a `timeout` method to `[mp3cast~ ]`. Default is 5000ms. If that is still too long, set it to a smaller value. Pd is still blocked when the other side is not responding, but it doesn't freeze (virtually) indefinitely anymore. I checked how `[netsend]` and `[tcpsend]` from iemnet do it, and they block, too, if the other end is not responding. I didn't try to be better than those.

**Comment by danomatika** [comment]
During the net objects overhaul for Pd, we also ran into this. On some systems, the default timeout can be as high as 5 or 10 minutes! Setting a default timeout is a good idea and the current for Pd's `[netsend]` & `[netreceive]` is 10 seconds: https://github.com/pure-data/pure-data/blob/master/src/x_net.c#L109

**Comment by Jackovic** [comment]
Hello,
I just compiled mp3cast~, but Pd still freeze whatever the timeout value (1000 or 10000)

To reproduce the freeze :

    start a stream to icecast2 server
    cut your network connection
    => Pd freeze
    
I get in console :
mp3cast~: 264 bytes skipped

If the connection is restored, Pd is restored too.

Pd patch (with Pd version 0.52.1) :
```
#N canvas 1217 1526 536 300 12;
#X obj 88 113 osc~ 440;
#X obj 88 208 mp3cast~;
#X obj 86 245 print;
#X obj 197 210 dac~;
#X msg 30 48 timeout 5000 \, icecast2 \, mountpoint titi.mp3 \, name
myname \, description mydesc \, passwd XXXX \, connect XXXX 80;
#X connect 0 0 1 0;
#X connect 0 0 1 1;
#X connect 0 0 3 0;
#X connect 0 0 3 1;
#X connect 1 0 2 0;
#X connect 4 0 1 0;
```

**Comment by reduzent** [comment]
Thanks for testing and feedback. I only now realize that I didn't address your original problem, but a freeze at connection time. Yours happens when a socket of an already established connection suddenly becomes unresponsive. I need to look into this.

**Comment by reduzent** [comment]
Now it shouldn't block Pd for more than 4 seconds. After this period, the connection to the streaming server is considered failed.

**Comment by Jackovic** [comment]
Yes I have this behavior, Pd freeze during ~4 seconds.
